### ISSUE TITLE
Aspyre as a service online (GUI) error

### ISSUE THREAD

**Issue by aethralis** [alix-tz/aspyre-gt#28]
Aspyre as a service online (GUI) https://aspyre-gui.herokuapp.com/ gives an error:

> Application error
> 
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
> heroku logs --tail

FF 111.0.1 (64-bit), Ubuntu 22.04

**Comment by alix-tz** [comment]
Hello! 
Sorry for the very late response! Heroku stopped offering free hosting services in November 2021, so I was no longer able to offer an already deployed version of the application. The only way to use it now is to run it on a local virtual server.
